routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//會員（須完成信箱驗證）
Route::group(['middleware' => ['email', 'auth']], function () {
    //權限清單
    //權限：permission.index.access
    Route::get('permission', [
        'as'         => 'permission.index',
        'uses'       => 'PermissionController@index',
        'middleware' => 'permission:permission.index.access',
    ]);
    //會員管理
    //權限：user.manage、user.view
    Route::resource('user', 'UserController', [
        'except' => [
            'create',
            'store',
        ],
    ]);
    //網站設定
    //權限：setting.edit
    Route::group(['middleware' => 'permission:setting.edit'], function () {
        //寄送測試信
        Route::post('send-test-mail', [
            'as'   => 'send-test-mail',
            'uses' => 'SettingController@sendTestMail',
        ]);
        Route::resource('setting', 'SettingController', [
            'only' => [
                'index',
                'update',
            ],
        ]);
    });
    //投票所管理
    //權限：voting-station.manage
    Route::group(['middleware' => 'permission:voting-station.manage'], function () {
        Route::resource('votingStation', 'Vote\VotingStationController', [
            'except' => 'destroy',
        ]);
    });

    //編輯選務人員
    //權限：election.edit-staff
    Route::get('election/{election}/edit-staff', [
        'as'   => 'election.edit-staff',
        'uses' => 'Vote\ElectionController@getEditStaff',
    ]);
    Route::post('election/{election}/edit-staff', [
        'as'   => 'election.edit-staff',
        'uses' => 'Vote\ElectionController@postEditStaff',
    ]);
    //編輯開票員
    //權限: election.edit-counting-staff 並且 使用者必須為該選舉之選務人員
    Route::group(['middleware' => 'permission:election.edit-counting-staff'], function () {
        Route::get('election/edit-counting-staff/{relation}', [
            'as'   => 'election.edit-counting-staff',
            'uses' => 'Vote\ElectionVotingStationRelationController@getEditCountingStaff',
        ]);
        Route::post('election/edit-counting-staff/{relation}', [
            'as'   => 'election.edit-counting-staff',
            'uses' => 'Vote\ElectionVotingStationRelationController@postEditCountingStaff',
        ]);
    });
    //編輯選舉之投票所
    //權限：election.edit-voting-station
    Route::get('election/{election}/edit-voting-station', [
        'as'   => 'election.edit-voting-station',
        'uses' => 'Vote\ElectionController@getEditVotingStation',
    ]);
    Route::post('election/{election}/edit-voting-station', [
        'as'   => 'election.edit-voting-station',
        'uses' => 'Vote\ElectionController@postEditVotingStation',
    ]);
    //開票
    //權限：election.count.ballot 且 須為該站開票員
    Route::group(['middleware' => 'permission:election.count.ballot'], function () {
        Route::post('ballot', [
            'as'   => 'ballot.store',
            'uses' => 'Vote\BallotController@store',
        ]);
    });
    //檢視網站記錄
    //權限：log-viewer.access
    Route::group(['middleware' => 'permission:log-viewer.access'], function () {
        Route::resource('websiteLog', 'WebsiteLogController', [
            'only' => [
                'index',
                'show',
            ],
        ]);
    });
    //網站資源樹狀圖
    //權限：tree.access
    Route::get('tree', [
        'as'         => 'tree.index',
        'uses'       => 'TreeController@index',
        'middleware' => 'permission:tree.access',
    ]);
    //Imgur圖片管理
    //權限：imgur-image.manage
    Route::group(['middleware' => 'permission:imgur-image.manage'], function () {
        Route::resource('imgurImage', 'ImgurImageController', [
            'only' => [
                'index',
                'show',
                'destroy',
            ],
        ]);
    });

    //會員資料
    Route::group(['prefix' => 'profile'], function () {
        //查看會員資料
        Route::get('/', [
            'as'   => 'profile',
            'uses' => 'ProfileController@getProfile',
        ]);
        //編輯會員資料
        Route::get('edit', [
            'as'   => 'profile.edit',
            'uses' => 'ProfileController@getEditProfile',
        ]);
        Route::put('update', [
            'as'   => 'profile.update',
            'uses' => 'ProfileController@updateProfile',
        ]);
        //修改密碼
        Route::get('change-password', [
            'as'   => 'profile.change-password',
            'uses' => 'ProfileController@getChangePassword',
        ]);
        Route::put('update-password', [
            'as'   => 'profile.update-password',
            'uses' => 'ProfileController@updatePassword',
        ]);
    });
    //保護機制
    Route::group(['prefix' => 'protect'], function () {
        //重新輸入密碼（保護頁面）
        Route::post('re-enter-password', [
            'as'   => 'protect.re-enter-password',
            'uses' => 'ProtectController@postReEnterPassword',
        ]);
    });
});

// 首頁
Route::get('/', 'HomeController@index')->name('home');
// 關於我們
Route::get('about', 'HomeController@about')->name('about');
// 服務條款
Route::get('term', 'HomeController@term')->name('term');
// 免責聲明
Route::get('disclaimer', 'HomeController@disclaimer')->name('disclaimer');
// 隱私權政策
Route::get('privacy', 'HomeController@privacy')->name('privacy');
// 常見問題
Route::get('faq', 'HomeController@faq')->name('faq');
// Queue狀態
Route::get('queue-status', 'QueueStatusController@index')->name('queue-status');
// 廣播測試
Route::get('broadcasting-test', 'BroadcastingController@test')->name('broadcasting-test');
Route::post('broadcasting-test/redis', 'BroadcastingController@testRedis')->name('broadcasting-test.redis');
Route::post('broadcasting-test/server', 'BroadcastingController@testBroadcastingServer')
    ->name('broadcasting-test.server');
Route::post('broadcasting-test/fire', 'BroadcastingController@findBroadcasting')->name('broadcasting-test.fire');

// 活動
Route::post('activity/{activity}/publish', 'Vote\ActivityController@publish')->name('activity.publish');
// 活動直播影片
//權限：activity.video.manage
Route::group(['middleware' => 'permission:activity.video.manage'], function () {
    Route::get('activity/{activity}/video', 'Vote\ActivityVideoController@show')->name('activity.video.show');
    Route::get('activity/{activity}/video/edit', 'Vote\ActivityVideoController@edit')->name('activity.video.edit');
    Route::post('activity/{activity}/video/edit', 'Vote\ActivityVideoController@update')
        ->name('activity.video.update');
});
Route::resource('activity', 'Vote\ActivityController', [
    'except' => [
        'destroy',
    ],
]);

// 選舉
Route::resource('election', 'Vote\ElectionController', [
    'except' => [
        'index',
        'destroy',
    ],
]);

// 選舉分組
// 顯示某一選舉的分組資料
Route::resource('category', 'Data\CategoryController');

Route::get('election/show-category/{categoryElectionRelation}', [
    'as'   => 'category.show-category',
    'uses' => 'Vote\CategoryElectionRelationController@show',
]);

Route::get('category-relation/create', 'Vote\CategoryElectionRelationController@create')
    ->name('category-relation.create');

Route::post('category-relation/store', 'Vote\CategoryElectionRelationController@store')
    ->name('category-relation.store');

Route::delete('category-relation/delete/{category}', 'Vote\CategoryElectionRelationController@destroy')
    ->name('category-relation.delete');

Route::get('category-relation/api', 'Vote\CategoryElectionRelationController@apiDataTable')
    ->name('category-relation.api.data');

Route::resource('group', 'Vote\GroupController', [
    'except' => [
        'index',
        'show',
    ],
]);

Route::resource('candidate', 'Vote\CandidateController', [
    'except' => [
        'index',
        'show',
    ],
]);

Route::resource('department', 'Data\DepartmentController', [
    'except' => [
        'destroy',
    ],
]);

Route::resource('college', 'Data\CollegeController', [
    'except' => [
        'destroy',
    ],
]);

Route::resource('notification', 'NotificationController');

// 開票頁面
Route::get('counting/manage', 'Vote\CountingController@manageIndex')->name('counting.manage.index');
Route::get('counting/manage/{evsRelation}', 'Vote\CountingController@manageShow')->name('counting.manage.show');
Route::post('counting/manage/{evsRelation}/close', 'Vote\CountingController@manageClose')
    ->name('counting.manage.close');
Route::get('counting/{activity}', 'Vote\CountingController@show')->name('counting.show');
Route::get('counting/{activity}/status', 'Vote\CountingController@status')->name('counting.status');

//公告
Route::resource('announcement', 'AnnouncementController');

Route::get('css-test', [
    'as'         => 'css-test',
    'middleware' => 'role:admin',
    function () {
        return view('bootstrap-test');
    },
]);

//API
Route::group(['prefix' => 'api'], function () {
    Route::post('user-list', [
        'as'   => 'api.user-list',
        'uses' => 'ApiController@userList',
    ]);
});
//Markdown API
Route::any('markdown', [
    'as'   => 'markdown.preview',
    'uses' => 'MarkdownApiController@markdownPreview',
]);
//Image API
Route::post('image/upload', [
    'as'   => 'image.upload',
    'uses' => 'ImageApiController@upload',
]);
Route::post('image/delete', [
    'as'   => 'image.delete',
    'uses' => 'ImageApiController@delete',
]);

Route::group(['namespace' => 'Auth'], function () {
    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::post('logout', 'LoginController@logout')->name('logout');
    // Registration Routes...

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="zh-Hant-TW">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    @inject('basePresenter', 'Hackersir\Presenters\BasePresenter')
    <title>{{ $pageTitle = $basePresenter->getPageTitle($__env->yieldContent('title')) }}</title>

    <!-- Metatag for Opengraph -->
    <meta property="og:url" content="{{ URL::full() }}" />
    <meta property="og:type" content="website" /> <!-- set profile in ot -->
    <meta property="og:title" content="{{ $pageTitle }}" />
    <meta property="og:description" content="{{ Config::get('site.desc') }}" />
    <meta property="og:image" content="{{ asset('img/hacker.png') }}" />
    <meta property="og:locale" content="zh_TW" />
    <meta property="og:locale:alternate" content="en_US" />
    <meta name="description" content="{{ Config::get('site.desc') }}" />

    <link rel="icon" href="{{ asset('favicon.png') }}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{{ asset(mix('build-css/bootswatch.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('build-css/sticky-footer.css')) }}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {!! Html::style('css/pnotify.custom.min.css') !!}
    {!! Minify::stylesheet('/css/app.css')->withFullUrl() !!}

    @yield('css')

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ Config::get('site.name') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                @include(config('laravel-menu.views.bootstrap-items'), ['items' => Menu::get('navBar')->roots()])
            </ul>
        </div>
    </div>
</nav>

@yield('content')

{{-- Footer --}}
<footer class="footer">
    <div class="container">
        <div class="text-center social-list">
            <a href="https://hackersir.org" title="黑客社社網" target="_blank"><span class="fa-stack fa-lg fa-2x"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-link fa-stack-1x fa-inverse"></i></span></a>
            <a href="https://www.facebook.com/HackerSir.tw" title="黑客社粉絲專頁" target="_blank"><span class="fa-stack fa-lg fa-2x"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-facebook fa-stack-1x fa-inverse"></i></span></a>
            <a href="https://www.youtube.com/channel/UCeDnuTpnq_4As-ceZiWsi4A" title="黑客社Youtube" target="_blank"><span class="fa-stack fa-lg fa-2x"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-youtube fa-stack-1x fa-inverse"></i></span></a>
            <a href="https://gitlab.com/HackerSir/VSDK" title="專案GitLab" target="_blank"><span class="fa-stack fa-lg fa-2x"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-git fa-stack-1x fa-inverse"></i></span></a>
            <a href="mailto:fcuhackersir@gmail.com" title="寄信給我們" target="_blank"><span class="fa-stack fa-lg fa-2x"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span></a>
        </div>
        <div class="text-center">
            Copyright &copy;	2016-{{ Carbon\Carbon::now()->year }} HackerSir 逢甲大學黑客社
            <ol class="footer-list">
                <li>{!! link_to_route('about', '關於我們') !!}</li>
                <li>{!! link_to_route('term', '服務條款 ') !!}</li>
                <li>{!! link_to_route('disclaimer', '免責聲明') !!}</li>
                <li>{!! link_to_route('privacy', '隱私權政策') !!}</li>
                <li>{!! link_to_route('faq', '常見問題') !!}</li>
                @if(Auth::guest())
                    <li>{!! link_to('login', '工作人員登入') !!}</li>
                @endif
            </ol>
        </div>
    </div>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

@if(env('Google_Analytics_Code'))
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ env('Google_Analytics_Code') }}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', '{{ env('Google_Analytics_Code') }}');
    </script>
@endif

@yield('js')

{{ Html::script("js/pnotify.custom.min.js") }}
{{ Html::script("js/pnotify-helper.js") }}

<script>
    @if(Session::has('global'))
        show_message('success', '{!! Session::get('global') !!}');
    @endif
    @if(Session::has('warning'))
        show_message('error', '{!! Session::get('warning') !!}');
    @endif
    @if(Session::has('info'))
        show_message('info', '{!! Session::get('info') !!}');
    @endif
</script>

</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('css')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/components/button.min.css">
    <style type="text/css">
        .navbar {
            margin-bottom: 0;
        }

        .jumbotron {
            min-height: calc(100vh - 50px);
            background: #ffd87a url("{{ asset('img/background.jpg') }}") no-repeat center center;
            background-size: cover;
        }

        .jumbotron-content {
            text-align: center;
            background: rgba(100, 100, 100, .6);
            margin-top: 20vh;
            margin-bottom: 20vh;
            padding-top: 40px;
            padding-bottom: 40px;
            border-radius: 20px;
            color: white;
        }

        a.button {
            font-size: 1.2em !important;
            margin-left: 20px !important;
            margin-right: 20px !important;
            margin-bottom: 5px !important;
        }

        a.button > i.fa {
            margin-bottom: 10px !important;
        }
    </style>
@endsection

@section('content')
    <div class="jumbotron">
        <div class="jumbotron-content container text-center">
            <h1>{{ Config::get('site.name') }}</h1>
            <p>{{ Config::get('site.desc') }}</p>
            <div class="text-center">
                <a href=" @if(isset($activity)) {{ route('activity.show', $activity) }} @else javascript:void(0) @endif " class="ui icon orange inverted massive button">
                    <i class="fa fa-commenting-o fa-2x" aria-hidden="true"></i><br/>選舉政見</a>
                <a href="{{ route('activity.index') }}" class="ui icon teal inverted massive button">
                    <i class="fa fa-ticket fa-2x" aria-hidden="true"></i><br/>選舉活動</a>
                <a href=" @if(isset($activity)) {{ route('counting.show', $activity) }} @else javascript:void(0) @endif "
                   class="ui icon red inverted massive button">
                    <i class="fa fa-podcast fa-2x" aria-hidden="true"></i><br/>開票直播</a>
                <a href="{{ route('announcement.index') }}" class="ui icon olive inverted massive button">
                    <i class="fa fa-bullhorn fa-2x" aria-hidden="true"></i><br/>網站公告</a>
            </div>
        </div>
    </div>
@endsection