routes/web.php
            'as'   => 'send-test-mail',
            'uses' => 'SettingController@sendTestMail',
        ]);
        Route::resource('setting', 'SettingController', [
            'only' => [
                'index',
                'update',
            ],
        ]);
    });
    //投票所管理
    //權限：voting-station.manage
    Route::group(['middleware' => 'permission:voting-station.manage'], function () {
        Route::resource('votingStation', 'Vote\VotingStationController', [
            'except' => 'destroy',
        ]);
    });

    //編輯選務人員
    //權限：election.edit-staff
    Route::get('election/{election}/edit-staff', [
        'as'   => 'election.edit-staff',
        'uses' => 'Vote\ElectionController@getEditStaff',
    ]);
    Route::post('election/{election}/edit-staff', [
        'as'   => 'election.edit-staff',
        'uses' => 'Vote\ElectionController@postEditStaff',
    ]);
    //編輯開票員
    //權限: election.edit-counting-staff 並且 使用者必須為該選舉之選務人員
    Route::group(['middleware' => 'permission:election.edit-counting-staff'], function () {
        Route::get('election/edit-counting-staff/{relation}', [
            'as'   => 'election.edit-counting-staff',
            'uses' => 'Vote\ElectionVotingStationRelationController@getEditCountingStaff',
        ]);
        Route::post('election/edit-counting-staff/{relation}', [
            'as'   => 'election.edit-counting-staff',
            'uses' => 'Vote\ElectionVotingStationRelationController@postEditCountingStaff',
        ]);
    });
    //編輯選舉之投票所
    //權限：election.edit-voting-station
    Route::get('election/{election}/edit-voting-station', [
        'as'   => 'election.edit-voting-station',
        'uses' => 'Vote\ElectionController@getEditVotingStation',
    ]);
    Route::post('election/{election}/edit-voting-station', [
        'as'   => 'election.edit-voting-station',
        'uses' => 'Vote\ElectionController@postEditVotingStation',
    ]);
    //開票
    //權限：election.count.ballot 且 須為該站開票員
    Route::group(['middleware' => 'permission:election.count.ballot'], function () {
        Route::post('ballot', [
            'as'   => 'ballot.store',
            'uses' => 'Vote\BallotController@store',
        ]);
    });
    //檢視網站記錄
    //權限：log-viewer.access
    Route::group(['middleware' => 'permission:log-viewer.access'], function () {
        Route::resource('websiteLog', 'WebsiteLogController', [
            'only' => [
                'index',
                'show',
            ],
        ]);
    });
    //網站資源樹狀圖
    //權限：tree.access
    Route::get('tree', [
        'as'         => 'tree.index',
        'uses'       => 'TreeController@index',
        'middleware' => 'permission:tree.access',
    ]);
    //Imgur圖片管理
    //權限：imgur-image.manage
    Route::group(['middleware' => 'permission:imgur-image.manage'], function () {
        Route::resource('imgurImage', 'ImgurImageController', [
            'only' => [
                'index',
                'show',
                'destroy',
            ],
        ]);
    });

    //會員資料
    Route::group(['prefix' => 'profile'], function () {
        //查看會員資料
        Route::get('/', [
            'as'   => 'profile',
            'uses' => 'ProfileController@getProfile',
        ]);
        //編輯會員資料
        Route::get('edit', [
            'as'   => 'profile.edit',
            'uses' => 'ProfileController@getEditProfile',
        ]);
        Route::put('update', [
            'as'   => 'profile.update',
            'uses' => 'ProfileController@updateProfile',
        ]);
        //修改密碼
        Route::get('change-password', [
            'as'   => 'profile.change-password',
            'uses' => 'ProfileController@getChangePassword',
        ]);
        Route::put('update-password', [
            'as'   => 'profile.update-password',
            'uses' => 'ProfileController@updatePassword',
        ]);
    });
    //保護機制
    Route::group(['prefix' => 'protect'], function () {
        //重新輸入密碼（保護頁面）
        Route::post('re-enter-password', [
            'as'   => 'protect.re-enter-password',
            'uses' => 'ProtectController@postReEnterPassword',
        ]);
    });
});

// 首頁
Route::get('/', 'HomeController@index')->name('home');
// 關於我們
Route::get('about', 'HomeController@about')->name('about');
// 服務條款
Route::get('term', 'HomeController@term')->name('term');
// 免責聲明
Route::get('disclaimer', 'HomeController@disclaimer')->name('disclaimer');
// 隱私權政策
Route::get('privacy', 'HomeController@privacy')->name('privacy');
// 常見問題
Route::get('faq', 'HomeController@faq')->name('faq');
// Queue狀態
Route::get('queue-status', 'QueueStatusController@index')->name('queue-status');
// 廣播測試
Route::get('broadcasting-test', 'BroadcastingController@test')->name('broadcasting-test');
Route::post('broadcasting-test/redis', 'BroadcastingController@testRedis')->name('broadcasting-test.redis');
Route::post('broadcasting-test/server', 'BroadcastingController@testBroadcastingServer')
    ->name('broadcasting-test.server');
Route::post('broadcasting-test/fire', 'BroadcastingController@findBroadcasting')->name('broadcasting-test.fire');

// 活動
Route::post('activity/{activity}/publish', 'Vote\ActivityController@publish')->name('activity.publish');
// 活動直播影片
//權限：activity.video.manage
Route::group(['middleware' => 'permission:activity.video.manage'], function () {
    Route::get('activity/{activity}/video', 'Vote\ActivityVideoController@show')->name('activity.video.show');
    Route::get('activity/{activity}/video/edit', 'Vote\ActivityVideoController@edit')->name('activity.video.edit');
    Route::post('activity/{activity}/video/edit', 'Vote\ActivityVideoController@update')
        ->name('activity.video.update');
});
Route::resource('activity', 'Vote\ActivityController', [
    'except' => [
        'destroy',
    ],
]);

// 選舉
Route::resource('election', 'Vote\ElectionController', [
    'except' => [
        'index',
        'destroy',
    ],
]);

// 選舉分組
// 顯示某一選舉的分組資料
Route::resource('category', 'Data\CategoryController');

Route::get('election/show-category/{categoryElectionRelation}', [
    'as'   => 'category.show-category',
    'uses' => 'Vote\CategoryElectionRelationController@show',
]);

Route::get('category-relation/create', 'Vote\CategoryElectionRelationController@create')
    ->name('category-relation.create');

Route::post('category-relation/store', 'Vote\CategoryElectionRelationController@store')
    ->name('category-relation.store');

Route::delete('category-relation/delete/{category}', 'Vote\CategoryElectionRelationController@destroy')
    ->name('category-relation.delete');

Route::get('category-relation/api', 'Vote\CategoryElectionRelationController@apiDataTable')
    ->name('category-relation.api.data');

Route::resource('group', 'Vote\GroupController', [
    'except' => [
        'index',
        'show',
    ],
]);

Route::resource('candidate', 'Vote\CandidateController', [
    'except' => [
        'index',
        'show',
    ],
]);

Route::resource('department', 'Data\DepartmentController', [
    'except' => [
        'destroy',
    ],
]);

Route::resource('college', 'Data\CollegeController', [
    'except' => [
        'destroy',
    ],
]);

Route::resource('notification', 'NotificationController');

// 開票頁面
Route::get('counting/manage', 'Vote\CountingController@manageIndex')->name('counting.manage.index');
Route::get('counting/manage/{evsRelation}', 'Vote\CountingController@manageShow')->name('counting.manage.show');
Route::post('counting/manage/{evsRelation}/close', 'Vote\CountingController@manageClose')
    ->name('counting.manage.close');
Route::get('counting/{activity}', 'Vote\CountingController@show')->name('counting.show');
Route::get('counting/{activity}/status', 'Vote\CountingController@status')->name('counting.status');

//公告
Route::resource('announcement', 'AnnouncementController');

Route::get('css-test', [
    'as'         => 'css-test',
    'middleware' => 'role:admin',
    function () {
        return view('bootstrap-test');
    },
]);

//API
Route::group(['prefix' => 'api'], function () {
    Route::post('user-list', [
        'as'   => 'api.user-list',
        'uses' => 'ApiController@userList',
    ]);
});
//Markdown API
Route::any('markdown', [
    'as'   => 'markdown.preview',
    'uses' => 'MarkdownApiController@markdownPreview',
]);
//Image API
Route::post('image/upload', [
    'as'   => 'image.upload',
    'uses' => 'ImageApiController@upload',
]);
Route::post('image/delete', [
    'as'   => 'image.delete',
    'uses' => 'ImageApiController@delete',
]);

Route::group(['namespace' => 'Auth'], function () {
    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::post('logout', 'LoginController@logout')->name('logout');
    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register')->name('register');
    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    //修改密碼
//    Route::get('password/change', 'PasswordController@getChangePassword')->name('password.change');
//    Route::put('password/change', 'PasswordController@putChangePassword')->name('password.change');
    //驗證信箱
    Route::get('resend', 'RegisterController@resendConfirmMailPage')->name('confirm-mail.resend');
    Route::post('resend', 'RegisterController@resendConfirmMail')->name('confirm-mail.resend');

app/Http/Controllers/AnnouncementController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Hackersir\Announcement;
use Illuminate\Http\Request;

class AnnouncementController extends Controller
{
    /**
     * AnnouncementController constructor.
     */
    public function __construct()
    {
        $this->middleware('permission:announcement.manage', [
            'except' => [
                'index',
                'show',
            ],
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $announcements = Announcement::orderBy('created_at', 'desc')->paginate();

        return view('announcement.index', compact('announcements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {
        return view('announcement.create-or-edit')->with('methodText', '新增');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'   => 'required|max:255',
            'message' => 'required|max:65535',
        ]);

        $announcement = Announcement::create([
            'title'   => $request->input('title'),
            'message' => $request->input('message'),
            'user_id' => Auth::user()->id,
        ]);

        return redirect()->route('announcement.show', $announcement)->with('global', '公告已建立');
    }

    /**
     * Display the specified resource.
     *
     * @param Announcement $announcement
     * @return \Illuminate\Http\Response
     */
    public function show(Announcement $announcement)
    {
        return view('announcement.show', compact('announcement'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Announcement $announcement
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Announcement $announcement)
    {
        return view('announcement.create-or-edit', compact('announcement'))->with('methodText', '修改');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Announcement $announcement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Announcement $announcement)
    {
        $this->validate($request, [
            'title'   => 'required|max:255',
            'message' => 'required|max:65535',
        ]);

        $announcement->update([
            'title'   => $request->input('title'),
            'message' => $request->input('message'),
        ]);

        return redirect()->route('announcement.show', $announcement)->with('global', '公告已更新');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Announcement $announcement
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Announcement $announcement)
    {
        $announcement->delete();

        return redirect()->route('announcement.index')->with('global', '公告已刪除');
    }
}

resources/views/announcement/create-or-edit.blade.php
@extends('app')

@section('title', $methodText. '公告')

@section('css')
    {!! Html::style('css/bootstrap-datetimepicker.css') !!}
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="well">
                    @if(isset($announcement))
                        {!! BootForm::openHorizontal(['sm' => [5, 7], 'lg' => [2, 10]])
                            ->action(route('announcement.update', $announcement))->put() !!}
                        {!! BootForm::bind($announcement) !!}
                    @else
                        {!! BootForm::openHorizontal(['sm' => [5, 7], 'lg' => [2, 10]])
                            ->action(route('announcement.store')) !!}
                    @endif
                    <fieldset>
                        <legend>{{ $methodText }}公告</legend>
                        {!! BootForm::text('標題', 'title')->required() !!}
                        {{--公告內容(Markdown) --}}
                        @include('common.markdown', [
                            'name' => 'message',
                            'labelName' => '內容',
                            'text' => isset($announcement) ? $announcement->message : null
                        ])
                        {{-- 提交按鈕 --}}
                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-7 col-lg-offset-2 col-lg-10">
                                {!! Form::submit($methodText, ['class' => 'btn btn-primary']) !!}
                                @if(isset($announcement))
                                    <a href="{{ route('announcement.show', $announcement) }}" class="btn btn-default">返回</a>
                                @else
                                    <a href="{{ route('announcement.index') }}" class="btn btn-default">返回</a>
                                @endif
                            </div>
                        </div>
                    </fieldset>
                    {!! BootForm::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    @include('common.markdown-js', ['name' => 'message'])
@endsection

resources/views/announcement/index.blade.php
@extends('app')

@section('title', '網站公告')

@section('content')
    <div class="container">
        @permission('announcement.manage')
        <a href="{{ route('announcement.create') }}" class="btn btn-primary"><i class="fa fa-plus-square"></i> 新增公告</a>
        @endpermission
        <div class="page-header">
            <h1>網站公告</h1>
        </div>
        <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
                <th class="text-center col-xs-2">公告日</th>
                <th class="text-center col-xs-9">標題</th>
            </tr>
            </thead>
            <tbody>
            @foreach($announcements as $announcement)
                <tr>
                    <td class="text-center">
                        {!! $announcement->updated_at->format('Y/m/d') !!}
                    </td>
                    <td>
                        {!! link_to_route('announcement.show', $announcement->title, $announcement) !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <div class="text-center">
        {!! $announcements->appends(Request::except(['page']))->render() !!}
    </div>
@endsection

resources/views/announcement/show.blade.php
@extends('app')

@section('title', $announcement->title)

@section('content')
    <div class="container">
        <div class="btn-margin-bottom">
            <a href="{{ route('announcement.index') }}" class="btn btn-default" role="button"><i class="fa fa-arrow-left"></i> 返回網站公告</a>
            @permission('announcement.manage')
            <a href="{{ route('announcement.edit', $announcement) }}" class="btn btn-primary" role="button"><i class="fa fa-cogs"></i> 編輯公告</a>
            {!! Form::open(['route' => ['announcement.destroy', $announcement], 'style' => 'display: inline', 'method' => 'DELETE', 'onSubmit' => "return confirm('確定要刪除此公告嗎？');"]) !!}
            <button type="submit" class="btn btn-danger">
                <i class="fa fa-trash"></i> 刪除公告
            </button>
            {!! Form::close() !!}
            @endpermission
        </div>
        <div class="page-header">
            <h1>{{ $announcement->title }}</h1>
        </div>
        <div class="row" style="margin: 0">
            <table class="table table-bordered">
                <tr>
                    <td class="text-center col-xs-4 col-md-2">公告時間</td>
                    <td class="col-xs-8 col-md-10">{!! $announcement->updated_at !!}</td>
                </tr>
                @if(Entrust::can('user.view'))
                    <tr class="danger">
                        <td class="text-center col-xs-4 col-md-2">發布者</td>
                        <td class="col-xs-8 col-md-10">
                            {!! link_to_route('user.show', $announcement->user->name, $announcement->user) !!}
                        </td>
                    </tr>
                @endif
                <tr>
                    <td class="text-center hidden-xs col-md-2">內容</td>
                    <td class="col-xs-12 col-md-10" colspan="2">
                        <div style="min-height: 40vh;">
                            {!! Hackersir\Helper\MarkdownHelper::translate($announcement->message) !!}
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
@endsection