routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//會員（須完成信箱驗證）
Route::group(['middleware' => ['email', 'auth']], function () {
    //權限清單
    //權限：permission.index.access
    Route::get('permission', [
        'as'         => 'permission.index',
        'uses'       => 'PermissionController@index',
        'middleware' => 'permission:permission.index.access',
    ]);
    //會員管理
    //權限：user.manage、user.view
    Route::resource('user', 'UserController', [
        'except' => [
            'create',
            'store',
        ],
    ]);
    //網站設定
    //權限：setting.edit
    Route::group(['middleware' => 'permission:setting.edit'], function () {
        //寄送測試信
        Route::post('send-test-mail', [
            'as'   => 'send-test-mail',
            'uses' => 'SettingController@sendTestMail',
        ]);
        Route::resource('setting', 'SettingController', [
            'only' => [
                'index',
                'update',
            ],
        ]);
    });
    //投票所管理
    //權限：voting-station.manage
    Route::group(['middleware' => 'permission:voting-station.manage'], function () {
        Route::resource('votingStation', 'Vote\VotingStationController', [
            'except' => 'destroy',
        ]);
    });

    //編輯選務人員
    //權限：election.edit-staff
    Route::get('election/{election}/edit-staff', [
        'as'   => 'election.edit-staff',
        'uses' => 'Vote\ElectionController@getEditStaff',
    ]);
    Route::post('election/{election}/edit-staff', [
        'as'   => 'election.edit-staff',
        'uses' => 'Vote\ElectionController@postEditStaff',
    ]);
    //編輯開票員
    //權限: election.edit-counting-staff 並且 使用者必須為該選舉之選務人員
    Route::group(['middleware' => 'permission:election.edit-counting-staff'], function () {
        Route::get('election/edit-counting-staff/{relation}', [
            'as'   => 'election.edit-counting-staff',
            'uses' => 'Vote\ElectionVotingStationRelationController@getEditCountingStaff',
        ]);
        Route::post('election/edit-counting-staff/{relation}', [
            'as'   => 'election.edit-counting-staff',
            'uses' => 'Vote\ElectionVotingStationRelationController@postEditCountingStaff',
        ]);
    });
    //編輯選舉之投票所
    //權限：election.edit-voting-station
    Route::get('election/{election}/edit-voting-station', [
        'as'   => 'election.edit-voting-station',
        'uses' => 'Vote\ElectionController@getEditVotingStation',
    ]);
    Route::post('election/{election}/edit-voting-station', [
        'as'   => 'election.edit-voting-station',
        'uses' => 'Vote\ElectionController@postEditVotingStation',
    ]);
    //開票
    //權限：election.count.ballot 且 須為該站開票員
    Route::group(['middleware' => 'permission:election.count.ballot'], function () {
        Route::post('ballot', [
            'as'   => 'ballot.store',
            'uses' => 'Vote\BallotController@store',
        ]);
    });
    //檢視網站記錄
    //權限：log-viewer.access
    Route::group(['middleware' => 'permission:log-viewer.access'], function () {
        Route::resource('websiteLog', 'WebsiteLogController', [
            'only' => [
                'index',
                'show',
            ],
        ]);
    });
    //網站資源樹狀圖
    //權限：tree.access
    Route::get('tree', [
        'as'         => 'tree.index',
        'uses'       => 'TreeController@index',
        'middleware' => 'permission:tree.access',
    ]);
    //Imgur圖片管理
    //權限：imgur-image.manage
    Route::group(['middleware' => 'permission:imgur-image.manage'], function () {
        Route::resource('imgurImage', 'ImgurImageController', [
            'only' => [
                'index',
                'show',
                'destroy',
            ],
        ]);
    });

    //會員資料
    Route::group(['prefix' => 'profile'], function () {
        //查看會員資料
        Route::get('/', [
            'as'   => 'profile',
            'uses' => 'ProfileController@getProfile',
        ]);
        //編輯會員資料
        Route::get('edit', [
            'as'   => 'profile.edit',
            'uses' => 'ProfileController@getEditProfile',
        ]);
        Route::put('update', [
            'as'   => 'profile.update',
            'uses' => 'ProfileController@updateProfile',
        ]);
        //修改密碼
        Route::get('change-password', [
            'as'   => 'profile.change-password',
            'uses' => 'ProfileController@getChangePassword',
        ]);
        Route::put('update-password', [
            'as'   => 'profile.update-password',
            'uses' => 'ProfileController@updatePassword',
        ]);
    });
    //保護機制
    Route::group(['prefix' => 'protect'], function () {
        //重新輸入密碼（保護頁面）
        Route::post('re-enter-password', [
            'as'   => 'protect.re-enter-password',
            'uses' => 'ProtectController@postReEnterPassword',
        ]);
    });
});

// 首頁
Route::get('/', 'HomeController@index')->name('home');
// 關於我們
Route::get('about', 'HomeController@about')->name('about');
// 服務條款
Route::get('term', 'HomeController@term')->name('term');
// 免責聲明
Route::get('disclaimer', 'HomeController@disclaimer')->name('disclaimer');
// 隱私權政策
Route::get('privacy', 'HomeController@privacy')->name('privacy');
// 常見問題
Route::get('faq', 'HomeController@faq')->name('faq');
// Queue狀態
Route::get('queue-status', 'QueueStatusController@index')->name('queue-status');
// 廣播測試
Route::get('broadcasting-test', 'BroadcastingController@test')->name('broadcasting-test');
Route::post('broadcasting-test/redis', 'BroadcastingController@testRedis')->name('broadcasting-test.redis');
Route::post('broadcasting-test/server', 'BroadcastingController@testBroadcastingServer')
    ->name('broadcasting-test.server');
Route::post('broadcasting-test/fire', 'BroadcastingController@findBroadcasting')->name('broadcasting-test.fire');

// 活動
Route::post('activity/{activity}/publish', 'Vote\ActivityController@publish')->name('activity.publish');
// 活動直播影片
//權限：activity.video.manage
Route::group(['middleware' => 'permission:activity.video.manage'], function () {
    Route::get('activity/{activity}/video', 'Vote\ActivityVideoController@show')->name('activity.video.show');
    Route::get('activity/{activity}/video/edit', 'Vote\ActivityVideoController@edit')->name('activity.video.edit');
    Route::post('activity/{activity}/video/edit', 'Vote\ActivityVideoController@update')
        ->name('activity.video.update');
});
Route::resource('activity', 'Vote\ActivityController', [
    'except' => [
        'destroy',
    ],
]);

// 選舉
Route::resource('election', 'Vote\ElectionController', [
    'except' => [
        'index',
        'destroy',
    ],
]);

// 選舉分組
// 顯示某一選舉的分組資料
Route::resource('category', 'Data\CategoryController');

Route::get('election/show-category/{categoryElectionRelation}', [
    'as'   => 'category.show-category',
    'uses' => 'Vote\CategoryElectionRelationController@show',
]);

Route::get('category-relation/create', 'Vote\CategoryElectionRelationController@create')
    ->name('category-relation.create');

Route::post('category-relation/store', 'Vote\CategoryElectionRelationController@store')
    ->name('category-relation.store');

Route::delete('category-relation/delete/{category}', 'Vote\CategoryElectionRelationController@destroy')
    ->name('category-relation.delete');

Route::get('category-relation/api', 'Vote\CategoryElectionRelationController@apiDataTable')
    ->name('category-relation.api.data');

Route::resource('group', 'Vote\GroupController', [
    'except' => [
        'index',
        'show',
    ],
]);

Route::resource('candidate', 'Vote\CandidateController', [
    'except' => [
        'index',
        'show',
    ],
]);

Route::resource('department', 'Data\DepartmentController', [
    'except' => [
        'destroy',
    ],
]);

Route::resource('college', 'Data\CollegeController', [
    'except' => [
        'destroy',
    ],
]);

Route::resource('notification', 'NotificationController');

// 開票頁面
Route::get('counting/manage', 'Vote\CountingController@manageIndex')->name('counting.manage.index');
Route::get('counting/manage/{evsRelation}', 'Vote\CountingController@manageShow')->name('counting.manage.show');
Route::post('counting/manage/{evsRelation}/close', 'Vote\CountingController@manageClose')
    ->name('counting.manage.close');
Route::get('counting/{activity}', 'Vote\CountingController@show')->name('counting.show');
Route::get('counting/{activity}/status', 'Vote\CountingController@status')->name('counting.status');

//公告
Route::resource('announcement', 'AnnouncementController');

Route::get('css-test', [
    'as'         => 'css-test',
    'middleware' => 'role:admin',
    function () {
        return view('bootstrap-test');
    },
]);

//API
Route::group(['prefix' => 'api'], function () {
    Route::post('user-list', [
        'as'   => 'api.user-list',
        'uses' => 'ApiController@userList',
    ]);
});
//Markdown API
Route::any('markdown', [
    'as'   => 'markdown.preview',
    'uses' => 'MarkdownApiController@markdownPreview',
]);
//Image API
Route::post('image/upload', [
    'as'   => 'image.upload',
    'uses' => 'ImageApiController@upload',
]);
Route::post('image/delete', [
    'as'   => 'image.delete',
    'uses' => 'ImageApiController@delete',
]);

Route::group(['namespace' => 'Auth'], function () {
    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::post('logout', 'LoginController@logout')->name('logout');
    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register')->name('register');
    // Password Reset Routes...

app/Http/Controllers/TreeController.php
<?php

namespace App\Http\Controllers;

use Hackersir\Activity;
use Hackersir\Election;
use Illuminate\Http\Request;

class TreeController extends Controller
{
    public function index(Request $request)
    {
        $this->validate($request, [
            'activity' => 'exists:activities,id',
            'election' => 'exists:elections,id',
        ]);
        //篩選條件
        //活動
        if ($request->has('activity')) {
            $activity = Activity::with(
                'elections.staffs',
                'elections.categoryElectionRelations.category.department',
                'elections.categoryElectionRelations.groups.candidates',
                'elections.electionVotingStationRelations.votingStation',
                'elections.electionVotingStationRelations.users'
            )->find($request->input('activity'));

            return view('tree.index', compact('activity'));
        }
        //選舉
        if ($request->has('election')) {
            $election = Election::with(
                'staffs',
                'categoryElectionRelations.category.department',
                'categoryElectionRelations.groups.candidates',
                'electionVotingStationRelations.votingStation',
                'electionVotingStationRelations.users'
            )->find($request->input('election'));

            return view('tree.index', compact('election'));
        }
        //全部顯示
        $activities = Activity::with(
            'elections.staffs',
            'elections.categoryElectionRelations.category.department',
            'elections.categoryElectionRelations.groups.candidates',
            'elections.electionVotingStationRelations.votingStation',
            'elections.electionVotingStationRelations.users'
        )->orderBy('vote_start', 'desc')->get();

        return view('tree.index', compact('activities'));
    }
}

resources/views/tree/activities.blade.php
{{--
    $activities: 活動清單
--}}
<ul>
    @foreach($activities as $activity)
        <li>
            <span class="label label-primary">活動</span>
            {{ link_to_route('activity.show', $activity->name, $activity, ['target' => '_blank']) }}
            <a href="{{ route('tree.index', ['activity' => $activity->id]) }}"><i class="fa fa-tree" aria-hidden="true"></i></a>
        </li>
        @include('tree.elections-in-activity', ['activity' => $activity])
    @endforeach
</ul>

resources/views/tree/candidates-in-group.blade.php
{{--
    $group: 候選組
--}}
<ul>
    @foreach($group->candidates as $candidate)
        <li>
            <span class="label label-primary">候選人</span>
            {{ $candidate->name }}
        </li>
    @endforeach
</ul>

resources/views/tree/categories-in-election.blade.php
{{--
    $election: 選舉
--}}
<ul>
    @foreach($election->categoryElectionRelations as $relation)
        <li>
            <span class="label label-primary">分組</span>
            {{ $relation->category->name }}
            @if($relation->category->department)
                <span class="label label-info">科系</span>
                [{{ $relation->category->department->abbreviation }}]
                {{ $relation->category->department->name }}
            @endif
        </li>
        @include('tree.groups-in-category-election-relation', ['categoryElectionRelations' => $relation])
    @endforeach
</ul>

resources/views/tree/elections-in-activity.blade.php
{{--
    $activity: 活動
--}}
<ul>
    @foreach($activity->elections as $election)
        <li>
            <span class="label label-primary">選舉</span>
            {{ link_to_route('election.show', $election->name, $election, ['target' => '_blank']) }}
            <a href="{{ route('tree.index', ['election' => $election->id]) }}"><i class="fa fa-tree" aria-hidden="true"></i></a>
            @if(count($election->staffs))
                <span class="label label-info">選務人員</span>
                @include('tree.user-list', ['users' => $election->staffs])
            @endif
        </li>
        @include('tree.categories-in-election', ['election' => $election])
        @include('tree.voting-stations-in-election', ['election' => $election])
    @endforeach
</ul>

resources/views/tree/groups-in-category-election-relation.blade.php
{{--
    $categoryElectionRelations: 分組 與 選舉 的關聯
--}}
<ul>
    @foreach($categoryElectionRelations->groups as $group)
        <li>
            <span class="label label-primary">候選組</span>
            {{ $group->number }}
        </li>
        @include('tree.candidates-in-group', ['group' => $group])
    @endforeach
</ul>

resources/views/tree/index.blade.php
@extends('app')

@section('title', '資源樹狀圖')

@section('content')
    <div class="container">
        {{-- Breadcrumb --}}
        <ol class="breadcrumb">
            現在位置：
            @if(isset($activity))
                <li>{{ link_to_route('tree.index', '資源樹狀圖') }}</li>
                <li class="active">{{ $activity->name }}</li>
            @elseif(isset($election))
                <li>{{ link_to_route('tree.index', '資源樹狀圖') }}</li>
                <li>{{ link_to_route('tree.index', $election->activity->name, ['activity' => $election->activity->id]) }}</li>
                <li class="active">{{ $election->name }}</li>
            @else
                <li class="active">資源樹狀圖</li>
            @endif
        </ol>
        <div class="page-header">
            <h1>資源樹狀圖</h1>
        </div>
        @if(isset($activity))
            @include('tree.elections-in-activity', ['activity' => $activity])
        @elseif(isset($election))
            @include('tree.categories-in-election', ['election' => $election])
            @include('tree.voting-stations-in-election', ['election' => $election])
        @else
            @include('tree.activities', ['activities' => $activities])
        @endif
    </div>
@endsection

resources/views/tree/user-list.blade.php
{{--
    $users: 使用者清單
--}}
@foreach($users as $user)
    {{ link_to_route('user.show', $user->name, $user, ['target' => '_blank']) }}，
@endforeach

resources/views/tree/voting-stations-in-election.blade.php
{{--
    $election: 選舉
--}}
<ul>
    @foreach($election->electionVotingStationRelations as $relation)
        <li>
            <span class="label label-default">投票所</span>
            {{ $relation->votingStation->name }}
            @if(count($relation->users))
                <span class="label label-info">開票員</span>
                @include('tree.user-list', ['users' => $relation->users])
            @endif
        </li>
    @endforeach
</ul>